# Generated by Django 5.1.6 on 2025-03-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='star_balance',
            field=models.IntegerField(default=0),
        ),
    ]
