services:
  web:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: django_web
    command: uvicorn ai_photo_bot.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:6.2-alpine"
    container_name: redis_broker
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: celery_worker
    command: celery -A ai_photo_bot worker -l info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env
