# Generated by Django 5.1.6 on 2025-02-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoto',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='file_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='file_unique_id',
            field=models.CharField(max_length=255),
        ),
    ]
