# Generated by Django 5.1.6 on 2025-02-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0002_remove_userphoto_timestamp_alter_userphoto_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='file_unique_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
