# Generated by Django 5.1.6 on 2025-02-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0004_alter_userphoto_file_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='file_unique_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
